const WEEKDAY_OPEN_HOURS = 9
const WEEKDAY_CLOSE_HOURS = 18
const WEEKEND_OPEN_HOURS = 10
const WEEKEND_CLOSE_HOURS = 16

export { WEEKDAY_OPEN_HOURS, WEEKDAY_CLOSE_HOURS, WEEKEND_OPEN_HOURS, WEEKEND_CLOSE_HOURS }
