const WEEKDAY_OPEN_HOURS = 9; // 9:00
const WEEKDAY_CLOSE_HOURS = 18; // 18:00
const WEEKEND_OPEN_HOURS = 10; // 10:00
const WEEKEND_CLOSE_HOURS = 16; // 16:00

export { WEEKDAY_OPEN_HOURS, WEEKDAY_CLOSE_HOURS, WEEKEND_OPEN_HOURS, WEEKEND_CLOSE_HOURS }